//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayKast_VFeb2026.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersArchive
    {
        public int ArchiveID { get; set; }
        public int OrderID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string OrderStatus { get; set; }
        public string TrackingNumber { get; set; }
        public System.DateTime DeletedAt { get; set; }
    }
}
