//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayKast_VFeb2026.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComments
    {
        public int CommentID { get; set; }
        public int ProductID { get; set; }
        public int MemberID { get; set; }
        public string CommentText { get; set; }
        public int Rating { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Products Products { get; set; }
    }
}
